### PR TITLE
Fixed #161 : Wrong folder structure after used zipWithPassword on And…

### LINKED ISSUE #161: Wrong folder structure after used zipWithPassword on Android
When I zip the folder "RootFolder" to "RootFolder.zip" using zipWithPassword, there is a wrong structure in the zip file. If only using zip, there is no problem.

**Before zip:**
RootFolder
---|__Folder
--------|__SubFolder
---------------|__1.txt
---------------|__2.txt

**After zipped:**
RootFolder.zip
---|__Folder
---|-----|__SubFolder
---|-----------|__1.txt
---|-----------|__2.txt
---|__SubFolder
----------|__1.txt
----------|__2.txt

### PR DESCRIPTION
**Pull request by kenyuwin**

### CODE REVIEW

File: android/src/main/java/com/rnziparchive/RNZipArchiveModule.java [hunk 1]
```diff
@@ -303,82 +304,70 @@ public void onCopyProgress(long bytesRead) {
...
       promise.reject(null, ex.getMessage());
       return;
     }
+
   }
 
-  @ReactMethod
-  public void zipWithPassword(final String fileOrDirectory, final String destDirectory, final String password,
-      final String encryptionMethod, final Promise promise) {
+  private void ProcessZip(final String fileOrDirectory, final String destDirectory, final ZipParameters parameters, final Promise promise) {
```
Comment (plrthink) [inline android/src/main/java/com/rnziparchive/RNZipArchiveModule.java]: It would be better to write method name in *lowerCamelCase* format, which is recommended by https://google.github.io/styleguide/javaguide.html#s5.2.3-method-names

```suggestion
  private void processZip(final String fileOrDirectory, final String destDirectory, final ZipParameters parameters, final Promise promise) {
```
